# FROM python:3.5
FROM amazon/aws-eb-python:3.4.2-onbuild-3.5.1
MAINTAINER khoale88 "lenguyenkhoa1988@gmail.com"

ENV KONG_BASE_URL "http://restbucks-api-sanjose-lb-1067926920.us-west-1.elb.amazonaws.com:9090"

# RUN pip install flask requests

# COPY . /var/app
# WORKDIR /var/app

# CMD python application.py
